### ISSUE TITLE
The description is not enough (and quite correct) ...

### ISSUE THREAD

**Issue by sunsande** [styxyk/touch-datepicker#1]
First of all - super component - thanks for sharing it!

It is not enough to `Copy TouchDatePicker.vue component into your project` ...

There are several dependencies : moment, font-awesome, vee-validate. 

Also I got errors on the console:  `Uncaught TypeError: Cannot read property 'dispatchEvent' of null` `TouchDatePicker.vue?b86e:280` when clicking on the buttons.

The calendar opened to the left side of the window when the control was put in a middle-centered container (i.e. the calendar showed left below from its text input - on the Hello World Template from vue.js CLI)

A better guide/description would be helpful.

And it would be nice  (at least on desktop) for the day/month/year inputs to be editable and tab-accessible.

Best regards!

**Comment by styxyk** [comment]
Thanks for pointing out the problems. I confess I haven't tested it in a new project (should have, but almost didn't expect anyone to be interested in it). I fixed the problems after installation and improved a bit the documentation. I hope it'll be of more help now. 

Cheers!
